### ISSUE TITLE
AttributeError: 'Settings' object has no attribute 'XPRO_BASE_URL'

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline-theme#4]
It looks like the theme has a dependency on a xpro-specific setting. 

```
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/core/handlers/exception.py", line 129, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/util/views.py", line 95, in wrapper
    return func(request, *args, **kwargs)
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/static_template_view/views.py", line 125, in render_500
    return HttpResponseServerError(render_to_string('static_templates/server-error.html', {}, request=request))
  File "/edx/app/edxapp/edx-platform/common/djangoapps/edxmako/shortcuts.py", line 178, in render_to_string
    return template.render(dictionary, request)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/edxmako/template.py", line 82, in render
    return self.mako_template.render_unicode(**context_dictionary)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/mako/template.py", line 478, in render_unicode
    return runtime._render(
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/mako/runtime.py", line 878, in _render
    _render_context(
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/mako/runtime.py", line 920, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/mako/runtime.py", line 947, in _exec_template
    callable_(context, *args, **kwargs)
  File "/tmp/mako_lms/84caac5afec1d5cec18c223971540436/main.html.py", line 345, in render_body
    runtime._include_file(context, (static.get_template_path('header.html')), _template_uri, online_help_token=online_help_token)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/mako/runtime.py", line 795, in _include_file
    callable_(ctx, **kwargs)
  File "/tmp/mako_lms/84caac5afec1d5cec18c223971540436/header.html.py", line 34, in render_body
    runtime._include_file(context, (static.get_template_path(relative_path='header/header.html')), _template_uri, online_help_token=online_help_token)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/mako/runtime.py", line 795, in _include_file
    callable_(ctx, **kwargs)
  File "/tmp/mako_lms/84caac5afec1d5cec18c223971540436/header/header.html.py", line 93, in render_body
    runtime._include_file(context, 'navbar-logo-header.html', _template_uri, online_help_token=online_help_token)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/mako/runtime.py", line 795, in _include_file
    callable_(ctx, **kwargs)
  File "/tmp/mako_lms/84caac5afec1d5cec18c223971540436/mitxonline-theme/lms/templates/header/navbar-logo-header.html.py", line 45, in render_body
    __M_writer(filters.html_escape(filters.decode.utf8(settings.XPRO_BASE_URL)))
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/conf/__init__.py", line 80, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'XPRO_BASE_URL'
```

**Comment by pdpinch** [comment]
In xPRO, I believe the value of that variable is the base URL of the Heroku application, i.e xpro-rc.xpro.mit.edu for RC, xpro.mit.edu for prod, etc. 

It is set here: https://github.com/mitodl/salt-ops/blob/ab5b7491de4fd5b63a432123b2a0d9f6b4919bb5/pillar/edx/ansible_vars/xpro.sls#L127

**Comment by pdpinch** [comment]
I think we should change the name of this setting to `MARKETING_SITE_BASE_URL` so it isn't xPRO specific. I opened a corresponding PR in ol-infrastructure https://github.com/mitodl/ol-infrastructure/issues/292
